allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@hot-updater/cli-tools@1.0.0-rc.3'
  - '@hot-updater/cloudflare@1.0.0-rc.5'
  - '@hot-updater/plugin-core@1.0.0-rc.3'
  - '@hot-updater/server@1.0.0-rc.3'
  - '@hot-updater/console@1.0.0-rc.10'
